name: Publish CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*' ]

jobs:
  publish:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to docker
        env:
          DOCKER_USER: rzuckerm
          DOCKER_TOKEN: {% raw %}${{secrets.DOCKER_TOKEN}}{% endraw %}
        run: echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          # Optionally strip `v` prefix
          strip_v: true

      - name: Show tag
        run: echo "Tag (without v) is {% raw %}${{steps.tag.outputs.tag}}{% endraw %}"

      - name: Build images
        run: make build DOCKER_TAG_SUFFIX=-{% raw %}${{steps.tag.outputs.tag}}{% endraw %}

      - name: Test images
        run: make test DOCKER_TAG_SUFFIX=-{% raw %}${{steps.tag.outputs.tag}}{% endraw %}

      - name: Publish images
        run: make publish DOCKER_TAG_SUFFIX=-{% raw %}${{steps.tag.outputs.tag}}{% endraw %}
